include:
  - docker-compose.kafka.yaml

services:
  order-service:
    image: ghcr.io/dls-soft2/order-service:latest
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - default

networks:
  default:
    driver: bridge
